### PR TITLE
Translating message sent by Telegram bot

### PR DESCRIPTION
**Pull request by saeeddarestany**
The language of the Telegram bot has been changed to English

### CODE REVIEW

**Review by hossinasaadi — APPROVED** [review]
Thanks you @isaeeed for your contribution🌹

**Comment by hossinasaadi** [comment]
Hi again @isaeeed , I reviewed your PR, we actually use multi translation in new version, so would you able to implementing it?

**Comment by saeeddarestany** [comment]
@hossinasaadi Hi . I'm not a golang developer, but I think I can do this. To support this feature, user language must be stored in a database. Currently, language is stored in cookies, so we need to change this. 
Login page language selection is interfered with if this is done.

It is possible to prioritize in this way

```
 if langConfig, err := s.settingService.GetLang(); err == nil && langConfig != "" {
			lang = langConfig
		} else if cookie, err := c.Request.Cookie("lang"); err == nil {
			lang = cookie.Value
		} else {
			lang = c.GetHeader("Accept-Language")
}

**Comment by hossinasaadi** [comment]
> @hossinasaadi Hi . I'm not a golang developer, but I think I can do this. To support this feature, user language must be stored in a database. Currently, language is stored in cookies, so we need to change this. Login page language selection is interfered with if this is done.
> 
> It is possible to prioritize in this way
> 
> ```
>  if langConfig, err := s.settingService.GetLang(); err == nil && langConfig != "" {
> 			lang = langConfig
> 		} else if cookie, err := c.Request.Cookie("lang"); err == nil {
> 			lang = cookie.Value
> 		} else {
> 			lang = c.GetHeader("Accept-Language")
> }
> ```

yes, you were right. thanks

**Pull request merged**
