### PR TITLE
Add API

### PR DESCRIPTION
**Pull request by hossinasaadi**
Postman collection attached

[X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)

### CODE REVIEW

**Comment by amihos** [comment]
This is awesome. Is it done? How to use it? Will you please provide documentation?

**Comment by rezafarokhi** [comment]
You've done a great work. Tanx a lot

**Comment by hossinasaadi** [comment]
> Hi There, when i use my domain name for API, In browser it returns json format and it's correct but when i use it in postman it just returns html format and content-type value in postman is html while in browser it's in right format (json)!
> 
> cause i use cdn i change the settings in cdn panel and but it didn't change the output format for postman and again it returns html in postman.
> 
> did you parse json in your code? or it is about cdn?

Hi @rezafarokhi , it’s about cdn, but you can convert from string anyway.

**Comment by amihos** [comment]
Hi @hossinasaadi 

I am having the same experience. Beside postman that shows html, I also tried Google script FetchURl Class which is for calling apis and the result was the same: HTML. The only way to see the correct Json output is to call the link via browser. Also, I noticed that the HTML does not contain JSON data.

Here is the output:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/assets/ant-design-vue@1.7.2/antd.min.css">
    <link rel="stylesheet" href="/assets/element-ui@2.15.0/theme-chalk/display.css">
    <link rel="stylesheet" href="/assets/css/custom.css?0.4.9">
    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    <title>登录</title>
</head>

<style>

    #app {
        padding-top: 100px;
    }

    h1 {
        text-align: center;
        color: #fff;
        margin: 20px 0 50px 0;
    }

    .ant-btn, .ant-input {
        height: 50px;
        border-radius: 30px;
    }

    .ant-input-affix-wrapper .ant-input-prefix {
        left: 23px;
    }

    .ant-input-affix-wrapper .ant-input:not(:first-child) {
        padding-left: 50px;
    }

    .selectLang{
        display: flex;
        text-align: center;
        justify-content: center;
    }

</style>
<body>
<a-layout id="app" v-cloak>
    <transition name="list" appear>
        <a-layout-content>
            <a-row type="flex" justify="center">
                <a-col :xs="22" :sm="20" :md="16" :lg="12" :xl="8">
                    <h1>登录</h1>
                </a-col>
            </a-row>
            <a-row type="flex" justify="center">
                <a-col :xs="22" :sm="20" :md="16" :lg="12" :xl="8">
                    <a-form>
                        <a-form-item>
                            <a-input v-model.trim="user.username" placeholder='用户名'
                                     @keydown.enter.native="login" autofocus>
                                <a-icon slot="prefix" type="user" style="color: rgba(0,0,0,.25)"/>
                            </a-input>
                        </a-form-item>
                        <a-form-item>
                            <a-input type="password" v-model.trim="user.password"
                                     placeholder='密码' @keydown.enter.native="login">
                                <a-icon slot="prefix" type="lock" style="color: rgba(0,0,0,.25)"/>
                            </a-input>
                        </a-form-item>
                        <a-form-item>
                            <a-button block @click="login" :loading="loading">登录</a-button>
                        </a-form-item>
                        <a-form-item>

                            <a-row justify="center" class="selectLang">
                                <a-col :span="4"><span>Language : </span></a-col>

                                <a-col :span="6">
                                    <a-select
                                            ref="selectLang"
                                            v-model="lang"
                                            @change="setLang(lang)"
                                    >
                                        <a-select-option  :value="l.value" label="China" v-for="l in supportLangs" >
                                            <span role="img" aria-label="l.name" v-text="l.icon"></span>
                                            &nbsp;&nbsp;<span v-text="l.name"></span>
                                        </a-select-option>
                                    </a-select>
                                </a-col>

                            </a-row>



                        </a-form-item>
                    </a-form>
                </a-col>
            </a-row>
        </a-layout-content>
    </transition>
</a-layout>

<script src="/assets/vue@2.6.12/vue.min.js"></script>
<script src="/assets/moment/moment.min.js"></script>
<script src="/assets/ant-design-vue@1.7.2/antd.min.js"></script>
<script src="/assets/base64/base64.min.js"></script>
<script src="/assets/axios/axios.min.js"></script>
<script src="/assets/qs/qs.min.js"></script>
<script src="/assets/qrcode/qrious.min.js"></script>
<script src="/assets/clipboard/clipboard.min.js"></script>
<script src="/assets/uri/URI.min.js"></script>
<script src="/assets/js/axios-init.js?0.4.9"></script>
<script src="/assets/js/util/common.js?0.4.9"></script>
<script src="/assets/js/util/date-util.js?0.4.9"></script>
<script src="/assets/js/util/utils.js?0.4.9"></script>
<script src="/assets/js/model/xray.js?0.4.9"></script>
<script src="/assets/js/model/models.js?0.4.9"></script>
<script src="/assets/js/langs.js"></script>
<script>
    const basePath = '\/';
    axios.defaults.baseURL = basePath;
</script>

<script>
    const leftColor = RandomUtil.randomIntRange(0x222222, 0xFFFFFF / 2).toString(16);
    const rightColor = RandomUtil.randomIntRange(0xFFFFFF / 2, 0xDDDDDD).toString(16);
    const deg = RandomUtil.randomIntRange(0, 360);
    const background = `linear-gradient(${deg}deg, #${leftColor} 10%, #${rightColor} 100%)`;
    document.querySelector('#app').style.background = background;
    const app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            loading: false,
            user: new User(),
            lang : ""
        },
        created(){
          this.lang = getLang();
        },
        methods: {
            async login() {
                this.loading = true;
                const msg = await HttpUtil.post('/login', this.user);
                this.loading = false;
                if (msg.success) {
                    location.href = basePath + 'xui/';
                }
            }
        }
    });
</script>
</body>
</html>

**Comment by amihos** [comment]
Update: I fixed the issue by calling login request first, getting cookie and use it in headers for getting inbounds call and it worked

**Comment by rezafarokhi** [comment]
> Update: I fixed the issue by calling login request first, getting cookie and use it in headers for getting inbounds call and it worked

How did you call login request?

**Comment by amihos** [comment]
> > Update: I fixed the issue by calling login request first, getting cookie and use it in headers for getting inbounds call and it worked
> 
> How did you call login request?

Just Call like this:
https://domain/login?username=yourusername&password=yourpassword

use thisheader in your request:

"headers": {
      "accept": "application/json, text/plain, */*",
      "content-type": "application/x-www-form-urlencoded; charset=UTF-8"
      },    
      "method": "POST",   
      "mode": "cors",   
      "credentials": "include" }

**Comment by Danaserver** [comment]
> > Update: I fixed the issue by calling login request first, getting cookie and use it in headers for getting inbounds call and it worked
> 
> How did you call login request?

HOw

> Update: I fixed the issue by calling login request first, getting cookie and use it in headers for getting inbounds call and it worked

لاگین کردم و {"success":true,"msg":"登录成功","obj":null} دریافت شد
کوکی هم دریافت شد به همراه session
برای get inbound فقط [Temporary Redirect] میده
curl_setopt_array($curl, array(
  CURLOPT_URL => "http://127.0.0.1:54321/xui/API/inbounds/get/9",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER =>$cookies['session']
));

**Comment by Danaserver** [comment]
وقت بخیر
امکان اینکه یک سمپل با CURL برای PHP بذارید هست؟

**Comment by Danaserver** [comment]
> وقت بخیر امکان اینکه یک سمپل با CURL برای PHP بذارید هست؟
انجام شد
curl_setopt($curl2, CURLOPT_HTTPHEADER, array("Cookie: session=".$cookies['session']));

**Comment by LordDeveloper** [comment]
Hi, When we use the Rest API to get the information of an inbound, it returns null. Is there a specific reason?

**Comment by LordDeveloper** [comment]
Also needed some routes:

**Comment by LordDeveloper** [comment]
Heeyy any body is here?

**Comment by LordDeveloper** [comment]
@hossinasaadi

**Comment by LordDeveloper** [comment]
@hossinasaadi

**Comment by hossinasaadi** [comment]
> @hossinasaadi

Why you mention repeatedly? 
if anyone can add these routes will add. 
also you can say it as request no and order!

**Comment by LordDeveloper** [comment]
Because it is necessary. If you do it for a fee, I can contact you on Telegram.

**Comment by mehdikhody** [comment]
#137

**Comment by SatanicDeveloper** [comment]
生成 xray 配置文件失败: json: error calling MarshalJSON for type json_util.RawMessage: invalid character '"' after object key:value pair
used rest api but pannel stopped. I think there was a problem with my json request body.
how to fix this??

**Comment by LordDeveloper** [comment]
> 生成 xray 配置文件失败: json: error calling MarshalJSON for type json_util.RawMessage: invalid character '"' after object key:value pair used rest api but pannel stopped. I think there was a problem with my json request body. how to fix this??

Go language logic :)

**Comment by miladkardgar** [comment]
سلام 
بعد از اضافه کردن کاربرا با استفاده از وب سرویس xray با خطا مواجه میشه و دیگه کار نمیکنه
راهی هست بشه متوجه شد که چرا بعد از اضافه کردن کاربران سیستم با خطا مواجه میشه ؟
یوزر به طور کامل و صحیح ایجاد میشه و ارسال میشه و در پنل با کلیه مشخصات وارد شده فعال میشه

> 


نمونه درخواست برای ایجاد کاربر:

> {"up":0,"down":0,"total":96636764160,"remark":"Mirzaei","enable":true,"expiryTime":1674061858000,"listen":null,"port":5129,"protocol":"vmess","settings":"{\"clients\":[{\"id\":\"df5001e7-080c-3603-bf56-0fbc26cf741f\",\"email\":\"5129xxx@xxx.xxx\",\"alterId\":0,\"limitIp\":1,\"totalGB\":0,\"expiryTime\":\"\"},{\"id\":\"d2a818df-51df-3377-95f5-18d210ceaf6f\",\"email\":\"5129xxxxx@xxxx.xxx\",\"alterId\":0,\"limitIp\":1,\"totalGB\":0,\"expiryTime\":\"\"}],\"disableInsecureEncryption\":false}","streamSettings":"{\"network\":\"ws\",\"security\":\"none\",\"wsSettings\":{\"acceptProxyProtocol\":false,\"path\":\"\\/\",\"headers\":[]}}","sniffing":"{\"enabled\":true,\"destOverride\":[\"http\",\"tls\"]}"}


اشتراک ایجاد شده

> 


جیسون اشتراک

`{
  "v": "2",
  "ps": "Mirzaei",
  "add": "xxxxxxxxxxx",
  "port": 4129,
  "id": "33c36149-ffe9-3474-948f-e932e067c703",
  "aid": 0,
  "net": "ws",
  "type": "none",
  "host": "",
  "path": "/",
  "tls": "none"
}`


حتی سرویس رو ریست کردم چند بار نصب کردم ولی هر باز بعد از ایجاد اشتراک xray با خطا مواجه میشه و کار نمیکنه هیچی
!!!!

**Comment by theMeysam** [comment]
> Postman collection attached
> 
> [X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)

Could you probably improve API to "settings", "streamSettings" and "sniffing" return object not string?

**Comment by rezafarokhi** [comment]
> سلام بعد از اضافه کردن کاربرا با استفاده از وب سرویس xray با خطا مواجه میشه و دیگه کار نمیکنه راهی هست بشه متوجه شد که چرا بعد از اضافه کردن کاربران سیستم با خطا مواجه میشه ؟ یوزر به طور کامل و صحیح ایجاد میشه و ارسال میشه و در پنل با کلیه مشخصات وارد شده فعال میشه
> 
> > 
> 
> نمونه درخواست برای ایجاد کاربر:
> 
> > {"up":0,"down":0,"total":96636764160,"remark":"Mirzaei","enable":true,"expiryTime":1674061858000,"listen":null,"port":5129,"protocol":"vmess","settings":"{"clients":[{"id":"df5001e7-080c-3603-bf56-0fbc26cf741f","email":"[5129xxx@xxx.xxx](mailto:5129xxx@xxx.xxx)","alterId":0,"limitIp":1,"totalGB":0,"expiryTime":""},{"id":"d2a818df-51df-3377-95f5-18d210ceaf6f","email":"[5129xxxxx@xxxx.xxx](mailto:5129xxxxx@xxxx.xxx)","alterId":0,"limitIp":1,"totalGB":0,"expiryTime":""}],"disableInsecureEncryption":false}","streamSettings":"{"network":"ws","security":"none","wsSettings":{"acceptProxyProtocol":false,"path":"\/","headers":[]}}","sniffing":"{"enabled":true,"destOverride":["http","tls"]}"}
> 
> اشتراک ایجاد شده
> 
> > 
> 
> جیسون اشتراک
> 
> `{ "v": "2", "ps": "Mirzaei", "add": "xxxxxxxxxxx", "port": 4129, "id": "33c36149-ffe9-3474-948f-e932e067c703", "aid": 0, "net": "ws", "type": "none", "host": "", "path": "/", "tls": "none" }`
> 
> حتی سرویس رو ریست کردم چند بار نصب کردم ولی هر باز بعد از ایجاد اشتراک xray با خطا مواجه میشه و کار نمیکنه هیچی !!!!

اگر پشت سی دی ان هست باید فقط از پورتای سی دی ان استفاده کنین و گرنه ارور میده

**Comment by LordDeveloper** [comment]
> هیچی



> متوجه



> سلام بعد از اضافه کردن کاربرا با استفاده از وب سرویس xray با خطا مواجه میشه و دیگه کار نمیکنه راهی هست بشه متوجه شد که چرا بعد از اضافه کردن کاربران سیستم با خطا مواجه میشه ؟ یوزر به طور کامل و صحیح ایجاد میشه و ارسال میشه و در پنل با کلیه مشخصات وارد شده فعال میشه
> 
> > 
> 
> نمونه درخواست برای ایجاد کاربر:
> 
> > {"up":0,"down":0,"total":96636764160,"remark":"Mirzaei","enable":true,"expiryTime":1674061858000,"listen":null,"port":5129,"protocol":"vmess","settings":"{"clients":[{"id":"df5001e7-080c-3603-bf56-0fbc26cf741f","email":"[5129xxx@xxx.xxx](mailto:5129xxx@xxx.xxx)","alterId":0,"limitIp":1,"totalGB":0,"expiryTime":""},{"id":"d2a818df-51df-3377-95f5-18d210ceaf6f","email":"[5129xxxxx@xxxx.xxx](mailto:5129xxxxx@xxxx.xxx)","alterId":0,"limitIp":1,"totalGB":0,"expiryTime":""}],"disableInsecureEncryption":false}","streamSettings":"{"network":"ws","security":"none","wsSettings":{"acceptProxyProtocol":false,"path":"\/","headers":[]}}","sniffing":"{"enabled":true,"destOverride":["http","tls"]}"}
> 
> اشتراک ایجاد شده
> 
> > 
> 
> جیسون اشتراک
> 
> `{ "v": "2", "ps": "Mirzaei", "add": "xxxxxxxxxxx", "port": 4129, "id": "33c36149-ffe9-3474-948f-e932e067c703", "aid": 0, "net": "ws", "type": "none", "host": "", "path": "/", "tls": "none" }`
> 
> حتی سرویس رو ریست کردم چند بار نصب کردم ولی هر باز بعد از ایجاد اشتراک xray با خطا مواجه میشه و کار نمیکنه هیچی !!!!

سلام وقتتون بخیر. مقدار headers نباید خالی باشه. اگه مقداری ندارید کلا حذفش کنین

**Comment by aladaghlou** [comment]
سلام. ممنون بابت به اشتراک گذاری این فایل جیسون. من همه متدهارو تست کردم درست کار میکنه فقط دریافت اطلاعات یک ردیف خطای 404 داد. اگر کسی حلش کرد بگه ممنون

**Comment by itsredrish** [comment]
سلام، خدا قوت
ظاهرا  API بدون اعتبارسنجی به request ها پاسخ میده :|
(غیر از http://localhost:1010/login که بررسی می‌کنه)

**Comment by aladaghlou** [comment]
> سلام، خدا قوت ظاهرا API بدون اعتبارسنجی به request ها پاسخ میده :| (غیر از http://localhost:1010/login که بررسی می‌کنه)

نه بدون کوکی خطا میده

**Comment by alirezax5** [comment]
> 

ی چیز همینطوری نوشتم

https://github.com/alirezax5/xuiapi/blob/main/xUiapi.php

$a = new \alirezax5\XUiApi\xUiapi('ip:port, 'username', 'pass');
$a->login();
$a->getInbounds()

**Comment by alirezax5** [comment]
> آقا کار نمیکنه دارم دیوونه میشم لطفا یکی به منه نوب سگ بگه که مشکلم کجاست ممنون!
> 
> $post = [ 'username' => 'admin', 'password' => 'admin' ];
> 
> $ch = curl_init('https://domain.cf:2053/login'); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); curl_setopt($ch, CURLOPT_POSTFIELDS, $post); curl_setopt($ch, CURLOPT_HTTPHEADER, array( 'accept: application/json, text/plain, /', 'content-type: application/x-www-form-urlencoded; charset=UTF-8' )); $resp = curl_exec($ch); curl_close($ch); var_dump($resp);

ی چیز همینطوری نوشتم

https://github.com/alirezax5/xuiapi/blob/main/xUiapi.php

$a = new \alirezax5\XUiApi\xUiapi('ip:port, 'username', 'pass');
$a->login();
$a->getInbounds()

**Comment by theMeysam** [comment]
> Postman collection attached
> 
> [X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)

How to get proxy uri by API???

**Comment by mehdikhody** [comment]
> > Postman collection attached
> > [X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)
> 
> How to get proxy uri by API???

For Vless:
```
vless://{client_id}@{server_ip}:{port}?type={transmission}&security=none&path={inbound_remark}
```

For Vmess::
```json
{
  "v": "2",
  "ps": "{inbound_remark}",
  "add": "{server_ip}",
  "port": {port},
  "id": "{client_id}",
  "aid": 0,
  "net": "{transmission}",
  "type": "none",
  "host": "",
  "path": "/",
  "tls": "none"
}
```
then Encode the json from above to Base64 format with a `vmess://` prefix.
```
vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ7aW5ib3VuZF9yZW1hcmt9IiwKICAiYWRkIjogIntzZXJ2ZXJfaXB9IiwKICAicG9ydCI6IHtwb3J0fSwKICAiaWQiOiAie2NsaWVudF9pZH0iLAogICJhaWQiOiAwLAogICJuZXQiOiAie3RyYW5zbWlzc2lvbn0iLAogICJ0eXBlIjogIm5vbmUiLAogICJob3N0IjogIiIsCiAgInBhdGgiOiAiLyIsCiAgInRscyI6ICJub25lIgp9
```

**Comment by OghabTeam** [comment]
> $a = new \alirezax5\XUiApi\xUiapi('ip:port, 'username', 'pass');
> $a->login();
> $a->getInbounds()

دمت گرم حاجی ولی خودت تستش کردی؟ چون برا من کار نکرد! ایدی تلتو میدی لطفا

**Comment by alirezax5** [comment]
> > $a = new \alirezax5\XUiApi\xUiapi('ip:port, 'username', 'pass');
> > $a->login();
> > $a->getInbounds()
> 
> دمت گرم حاجی ولی خودت تستش کردی؟ چون برا من کار نکرد! ایدی تلتو میدی لطفا

کار کردن که کار میده
باید مسیر پنلت, یوزر و پس درست وارد کنی 
فقط تست هاتو توی یک سرور تست انجام بده
https://t.me/alireza_x5_bot

**Comment by OghabTeam** [comment]
لاگ های مربوطه به api کجا ذخیره میشه؟ من یه مشکلی دارم جدیدا ریکوییست رو دریافت نمیکنه سرور میخوام ببینم چشه!!

**Comment by amira133** [comment]
hi, there
Is there any documentation  how to work with panel?(persian or english or ...)

**Comment by userisamir** [comment]
@hossinasaadi 
To Binaziri
Worked like a charm.

**Comment by alirayaneh** [comment]
missied "clientStats" on get inbound 
for example 
.../get/1
return null for "clientStats"

**Comment by mostafa9112** [comment]
> > > Postman collection attached
> > > [X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)
> > 
> > 
> > How to get proxy uri by API???
> 
> For Vless:
> 
> ```
> vless://{client_id}@{server_ip}:{port}?type={transmission}&security=none&path={inbound_remark}
> ```
> 
> For Vmess::
> 
> ```json
> {
>   "v": "2",
>   "ps": "{inbound_remark}",
>   "add": "{server_ip}",
>   "port": {port},
>   "id": "{client_id}",
>   "aid": 0,
>   "net": "{transmission}",
>   "type": "none",
>   "host": "",
>   "path": "/",
>   "tls": "none"
> }
> ```
> 
> then Encode the json from above to Base64 format with a `vmess://` prefix.
> 
> ```
> vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ7aW5ib3VuZF9yZW1hcmt9IiwKICAiYWRkIjogIntzZXJ2ZXJfaXB9IiwKICAicG9ydCI6IHtwb3J0fSwKICAiaWQiOiAie2NsaWVudF9pZH0iLAogICJhaWQiOiAwLAogICJuZXQiOiAie3RyYW5zbWlzc2lvbn0iLAogICJ0eXBlIjogIm5vbmUiLAogICJob3N0IjogIiIsCiAgInBhdGgiOiAiLyIsCiAgInRscyI6ICJub25lIgp9
> ```

Please explain where to get the required values?

**Comment by OghabTeam** [comment]
> Also needed some routes:
> 
> 1. Getting a specific client details:
>    `/inbounds/:inboundId/clients/:clientId`
>    or
>    `/clients/:id`
> 2. Delete a inbound specific client:
>    `/inbounds/:inboundId/clients/delete/:id`
>    or
>    `/clients/delete/:id`
> 3. Updating a inbound specific client [POST]:
>    `/inbounds/clients/update/:id` (payload)
>    or
>    `/cliends/update/:id` (payload)
> 4. Creating a client for a inbound[POST]:
>    `/inbounds/:id/clients/create` (payload)
> 5. Getting a specific inbound clientStats:
>    `/inbounds/:id/clients`
> 
> I think this will be very easy for you :)

داداش تونستی راهی برا اینا پیدا کنی با php ?!

**Comment by mojtabaghasemi** [comment]
سلام
چجوری میتونم حجم استفاده شده client ها رو بگیرم ؟

**Comment by younesatesh** [comment]
> Postman collection attached
> 
> [X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)

Hello, how do I use it? Look at the example below and see if it is correct or not.
https://mydomin/apps/v2.json?login/url=myserver:port&username=younes&password=1233

**Comment by mostafa9112** [comment]
> > Postman collection attached
> > [X-UI API.postman_collection3.zip](https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip)
> 
> Hello, how do I use it? Look at the example below and see if it is correct or not. https://mydomin/apps/v2.json?login/url=myserver:port&username=younes&password=1233

for login:
http://SERVERIP:PORT/PanelAddress/login?username=USERNAME&password=PASSWORD

use php CURL

**Comment by younesatesh** [comment]
> http://SERVERIP:PORT/PanelAddress/login?username=USERNAME&password=PASSWORD

Are you sure brother? Because it didn't work for me

**Comment by YOUSSSOF** [comment]
> 

should it necessarily done by a domain? I tried every possible port with ip address but it just gave 401. my mind is fucked up right now please help me.

**Comment by mostafa9112** [comment]
> > http://SERVERIP:PORT/PanelAddress/login?username=USERNAME&password=PASSWORD
> 
> Are you sure brother? Because it didn't work for me

Yes but use this class:

**Comment by mostafa9112** [comment]
@hossinasaadi

plz update the api for more control and get mor info like get users

**Comment by mostafa9112** [comment]
> سلام چجوری میتونم حجم استفاده شده client ها رو بگیرم ؟

سلام باید با متد getinbunds تمام کانفیگ ها رو بگیرید و در فایل جیسون دریافتی در بخش clientStats مصرف تمام کلاینت ها رو نوشته حتی کلاینت هایی که حذف شده اند

**Comment by mojtabaghasemi** [comment]
سلام وقت بخیر ، وقتی با وب سرویس یوزر ساخته میشه پنل با خطا مواجه میشه و دیگه کار نمیکنه .
Screenshot from 2022-12-29 12-44-31

**Pull request merged**
