### PR TITLE
add vless limit ip

### PR DESCRIPTION
**Pull request by proshir**
Hello my hero. I added VLESS .
In the next step, I want to make a change in the code that after checking the ips, if a user has less ip than his maximum, if he himself turned him off, he will be reactivated. I think it is better to separate the activity of a user from the activity that this job sets.
Of course, I don't know, maybe you have worked on this issue yourself and want to commit it in the next steps.
Thank you.

### CODE REVIEW

**Comment by saroo98** [comment]
> 

Thank you mate. Adding the reactivation would also be great! Otherwise the owner must reactivate it, which is a great burden tbh

**Comment by hossinasaadi** [comment]
@proshir do you run and test the project?
have several problems!

**Comment by proshir** [comment]
yes i did it .
Can you tell me exactly what the problems are?

**Comment by hossinasaadi** [comment]
> yes i did it . Can you tell me exactly what the problems are?

`web/job/check_clinet_ip_job.go:49:40: syntax error: unexpected if at end of statement
`

**Comment by proshir** [comment]
Sorry, I think I made a mistake during the commit. 
i commit right thing now

**Comment by proshir** [comment]
I made a mistake while committing it, my hand hit the keyboard and this was added XD

**Comment by proshir** [comment]
for next step i think you should merge multi user with main to continue " Reactivating users "
i think it's better to separate enabled users with blocking by ip limits

**Comment by proshir** [comment]
But now, with your permission, I want to do this only in this mode, and later we will add it in multi-user mode.

**Comment by proshir** [comment]
Why didn't you merge this? Is there still a problem? I have done all the tests

**Review by hossinasaadi — APPROVED** [review]

**Review by a7one — COMMENTED** [review]
hi because of intranet in iran we have to use 2vps . one in iran and one in europ
and tunnel from iran vps to eu vps..because of that all clinet have ip of iran vps and in eu vps we see iran vps in log .... so if 2 user connect x-ui just see 1 ip and thats iran ip and it dosent limit user ...it would be good if there is a way if two user with same ip connect to server x-ui limit that..

**Comment by a7one** [comment]
bro please update install.sh and x-ui.sh so pepole can install new version

**Comment by hossinasaadi** [comment]
> bro please update install.sh and x-ui.sh so pepole can install new version

It’s updated

**Pull request merged**
